import Foundation

/// Renders the policy as a block for CLAUDE.md / AGENTS.md so the agent's
/// default matches the architecture instead of its training-data prior.
public enum AgentInstructions {
    public static func render(policy: FrameworkPolicy = .standard,
                              catalogue: [Screen] = Fixture.catalogue) -> String {
        let agent = policy.profile(for: .agent)
        let evaluator = Evaluator(policy: policy)
        let verdicts = evaluator.verdicts(for: catalogue, author: .agent)

        func list(_ framework: Framework) -> String {
            policy.signals
                .filter { $0.favours == framework }
                .sorted { ($0.weight, $0.trait.rawValue) > ($1.weight, $1.trait.rawValue) }
                .map { signal in
                    let effective = signal.weight * agent.multiplier(for: signal.axis)
                    return "- `\(signal.trait.rawValue)` — \(signal.trait.summary) (\(signal.axis.rawValue), effective weight \(format(effective)))"
                }
                .joined(separator: "\n")
        }

        var lines: [String] = []
        lines.append("## UI framework rule")
        lines.append("")
        lines.append("Generated by UIFrameworkPolicy. Do not hand-edit; change the policy and re-render.")
        lines.append("")
        lines.append("Default framework for a new screen: **\(policy.defaultFramework.rawValue)**.")
        lines.append("You are the `agent` author. Under that profile ergonomics counts ×\(format(agent.ergonomics)) and verifiability counts ×\(format(agent.verifiability)); a reviewer must be able to predict the layout from your source without running it.")
        lines.append("")
        lines.append("Before writing a screen, classify it with the traits below, sum the effective weights per framework, and pick the higher one. If the scores are within \(format(policy.tieMargin)) of each other, use the default and say so in the PR description.")
        lines.append("")
        lines.append("### Signals for UIKit")
        lines.append(list(.uiKit))
        lines.append("")
        lines.append("### Signals for SwiftUI")
        lines.append(list(.swiftUI))
        lines.append("")
        lines.append("### Catalogue verdicts (agent profile)")
        for verdict in verdicts {
            let tie = verdict.decisive ? "" : " (tie → default)"
            lines.append("- \(verdict.screen.name): **\(verdict.framework.rawValue)** — SwiftUI \(format(verdict.swiftUIScore)) vs UIKit \(format(verdict.uiKitScore))\(tie)")
        }
        lines.append("")
        lines.append("### Verification")
        lines.append("- Every UIKit screen ships with a snapshot test at the design's reference size.")
        lines.append("- Every SwiftUI screen builds against the minimum deployment target with zero `#available` shims in the view body.")
        lines.append("- Never mix: one screen, one framework. Bridge at the screen boundary with `UIHostingController` or `UIViewRepresentable`, never inside a view.")
        return lines.joined(separator: "\n")
    }

    static func format(_ value: Double) -> String {
        if value == value.rounded() { return String(Int(value)) }
        var text = String(format: "%.2f", value)
        while text.hasSuffix("0") { text.removeLast() }
        return text
    }
}
